#!/bin/bash -i

# install Node Version Manager (NVM)
printf '\033[1mNode\nInstalling NVM…\033[0m\n'
# run the script
curl -so- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
# fix `.bashrc` part generated by the script
# replace `\.` with `.` (for some reason they thought `\.` is used for sourcing shell scripts)
perl -pe 's/(\$NVM_DIR\/(nvm\.sh|bash_completion)"\s?\]\s?\&\&\s?)(\\.)(\s?"\$NVM_DIR\/)/$1.$4/g' -i ~/.bashrc
# reload
. ~/.bashrc

# install the latest LTS version
nvm install --lts

# reload PATH again
. ~/.bashrc
