- keyboards: ['AT Translated Set 2 keyboard']

  keymap:
    # elongate shift on US international keyboard layout
    102nd: leftshift
    # elongate enter on US international keyboard layout
    backslash: enter
    # F7–F12 are rarely used, replace with more frequently used keys
    f12: insert
    f10: pageup
    f11: pagedown
    f7: previoussong
    f8: playpause
    f9: nextsong
  layers:
    # make replaced keys available under secondary mini-layer
    - modifiers: ['rightalt']
      keymap:
        backslash: backslash
        f12: f12
        f10: f10
        f11: f11
        f7: f7
        f8: f8
        f9: f9
    - modifiers: ['rightshift']
      keymap:
        backslash: backslash
